"""empty message

Revision ID: 232ee7fa0e1c
Revises: c16f043be26a
Create Date: 2020-12-14 10:39:19.668853

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232ee7fa0e1c'
down_revision = 'c16f043be26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False, default=datetime.utcnow),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('followers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False, default=datetime.utcnow),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follow_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'follow_id')
    )

    op.create_table('pub__rec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False, default=datetime.utcnow),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('recipe_type', sa.String(length=16), nullable=True),
    sa.Column('recipe_genre', sa.String(length=32), nullable=True),
    sa.Column('picture', sa.String(length=20), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['origin_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin_id')
    )
    op.create_table('user__rec',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('borrowed', sa.Boolean(), nullable=False, default='false'),
    sa.Column('borrowed_dates', sa.JSON(), nullable=True, default='{}'),
    sa.Column('downloaded', sa.Boolean(), nullable=True, default='false'),
    sa.Column('downloaded_dates', sa.JSON(), nullable=False, default='[]'),
    sa.Column('in_menu', sa.Boolean(), nullable=False, default='false'),
    sa.Column('eaten', sa.Boolean(), nullable=False, default='false'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__rec')
    op.drop_table('pub__rec')
    op.drop_table('followers')
    op.drop_table('actions')
    # ### end Alembic commands ###
