"""empty message

Revision ID: e1807c79fb34
Revises: b7330990195b
Create Date: 2021-01-29 16:27:18.706005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '386ea7691841'
down_revision = 'b4eb7f229198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ####
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.alter_column('date_joined',
        #                       existing_type=sa.DATETIME(), nullable=False,
        #                       existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        #                       server_default=sa.text('(CURRENT_TIMESTAMP)'))
        # batch_op.alter_column('extras',
        #                       existing_type=sqlite.JSON(),
        #                       nullable=False, server_default='[]')
        # batch_op.alter_column('grocery_list',
        #                       existing_type=sqlite.JSON(),
        #                       nullable=False, server_default='[]')
        # batch_op.alter_column('pantry',
        #                       existing_type=sqlite.JSON(),
        #                       nullable=False,
        #                       existing_server_default=sa.text("'{}'"), server_default='{}')
        batch_op.alter_column('history',
                              existing_type=sqlite.JSON(),
                              nullable=False, server_default='{}')
        batch_op.drop_column('recipe_hide')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_hide', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.alter_column('history',
                              existing_type=sqlite.JSON(),
                              nullable=False, server_default=sa.text("'[]'"))
        # batch_op.alter_column('pantry',
        #                       existing_type=sqlite.JSON(),
        #                       nullable=True,
        #                       existing_server_default=sa.text("'{}'"))
        # batch_op.alter_column('grocery_list',
        #                       existing_type=sqlite.JSON(),
        #                       nullable=True)
        # batch_op.alter_column('extras',
        #                       existing_type=sqlite.JSON(),
        #                       nullable=True)
        # batch_op.alter_column('date_joined',
        #                       existing_type=sa.DATETIME(),
        #                       nullable=True,
        #                       existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###
