"""empty message

Revision ID: 7d1b9d763a3c
Revises: 232ee7fa0e1c
Create Date: 2020-12-14 15:22:27.807829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1b9d763a3c'
down_revision = '232ee7fa0e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__pub_rec',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('borrowed', sa.Boolean(), nullable=True),
    sa.Column('borrowed_dates', sa.JSON(), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=True),
    sa.Column('downloaded_dates', sa.JSON(), nullable=True),
    sa.Column('in_menu', sa.Boolean(), nullable=False),
    sa.Column('eaten', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['pub__rec.p_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_see', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('feed_show', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('grocery_bills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pro2', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('pro3', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('pro4', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('recipe_hide', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('subscription', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription')
        batch_op.drop_column('recipe_hide')
        batch_op.drop_column('public')
        batch_op.drop_column('pro4')
        batch_op.drop_column('pro3')
        batch_op.drop_column('pro2')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('grocery_bills')
        batch_op.drop_column('feed_show')
        batch_op.drop_column('feed_see')

    op.drop_table('user__pub_rec')
    # ### end Alembic commands ###
