"""empty message

Revision ID: 96e2493e67bd
Revises: be94812c28d2
Create Date: 2020-12-14 23:24:52.281966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '96e2493e67bd'
down_revision = 'be94812c28d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    with op.batch_alter_table('recipes', schema=None) as batch_op:
#        batch_op.add_column(sa.Column('recipe_genre', sa.String(length=32), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_joined',
               existing_type=sa.DATETIME(),
               nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('pantry',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pantry',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('date_joined',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('recipe_genre')

    # ### end Alembic commands ###
