"""empty message

Revision ID: a403680cb856
Revises: be94812c28d2
Create Date: 2020-12-16 21:37:24.189178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a403680cb856'
down_revision = 'be94812c28d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__act',
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=False, default=False),
    sa.ForeignKeyConstraint(['act_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user__pub_rec',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('borrowed', sa.Boolean(), nullable=False, default=False),
    sa.Column('borrowed_dates', sa.JSON(), nullable=False, default={}),
    sa.Column('downloaded', sa.Boolean(), nullable=False, default=False),
    sa.Column('downloaded_dates', sa.JSON(), nullable=False, default=[]),
    sa.Column('in_menu', sa.Boolean(), nullable=False, default=False),
    sa.Column('eaten', sa.Boolean(), nullable=False, default=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['pub__rec.p_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harmony_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recipe_ids', sa.JSON(), nullable=False, server_default='[]'))

    with op.batch_alter_table('pub__rec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ogusername', sa.String(length=64), nullable=True))  # Must add username

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originator', sa.Integer(), nullable=True))  # must add to recipe
        batch_op.add_column(sa.Column('times_eaten', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('user__rec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_eaten', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__rec', schema=None) as batch_op:
        batch_op.drop_column('times_eaten')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('times_eaten')
        batch_op.drop_column('originator')

    with op.batch_alter_table('pub__rec', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('credit')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('recipe_ids')
        batch_op.drop_column('harmony_score')

    op.drop_table('user__pub_rec')
    op.drop_table('user__act')
    # ### end Alembic commands ###
