"""empty message

Revision ID: ad5bfd33081b
Revises: a403680cb856
Create Date: 2020-12-17 10:04:09.102095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ad5bfd33081b'
down_revision = 'a403680cb856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__pub_rec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_eaten', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__pub_rec', schema=None) as batch_op:
        batch_op.drop_column('times_eaten')

    # ### end Alembic commands ###
