"""empty message

Revision ID: b7330990195b
Revises: ccd86a721b91
Create Date: 2020-12-31 20:25:13.465284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b7330990195b'
down_revision = 'ccd86a721b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pub__rec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('price', sa.JSON(), nullable=False, server_default='{}'))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('price', sa.JSON(), nullable=False, server_default='{}'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reports', sa.JSON(), nullable=False, server_default='{"Reports": [], "Reported": []}'))
        batch_op.add_column(sa.Column('timezone', sa.String(length=60), nullable=True))
        batch_op.drop_column('password')

    with op.batch_alter_table('user__pub_rec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('user__rec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__rec', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    with op.batch_alter_table('user__pub_rec', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=60), nullable=False))
        batch_op.alter_column('pantry',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('grocery_list',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('extras',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.drop_column('timezone')
        batch_op.drop_column('reports')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.drop_column('price')
        batch_op.drop_column('options')

    with op.batch_alter_table('pub__rec', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('options')

    # ### end Alembic commands ###
