"""empty message

Revision ID: be94812c28d2
Revises: 232ee7fa0e1c
Create Date: 2020-12-14 16:58:10.335774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'be94812c28d2'
down_revision = '232ee7fa0e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_see', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('feed_show', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('grocery_bills', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('ingredients', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('pro2', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('pro3', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('pro4', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('recipe_hide', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('subscription', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.drop_column('friend_requests')
        batch_op.drop_column('friends')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friends', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('friend_requests', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.drop_column('subscription')
        batch_op.drop_column('recipe_hide')
        batch_op.drop_column('public')
        batch_op.drop_column('pro4')
        batch_op.drop_column('pro3')
        batch_op.drop_column('pro2')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('grocery_bills')
        batch_op.drop_column('feed_show')
        batch_op.drop_column('feed_see')

    # ### end Alembic commands ###
