"""empty message

Revision ID: c16f043be26a
Revises: 
Create Date: 2020-12-14 09:57:21.393941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16f043be26a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('harmony_preferences', sa.JSON(), nullable=True),
    sa.Column('pro', sa.Boolean(), nullable=False),
    sa.Column('grocery_list', sa.JSON(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('friend_requests', sa.JSON(), nullable=False),
    sa.Column('friends', sa.JSON(), nullable=False),
    sa.Column('pantry', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aisles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=20), nullable=True),
    sa.Column('in_menu', sa.Boolean(), nullable=False),
    sa.Column('eaten', sa.Boolean(), nullable=False),
    sa.Column('recipe_type', sa.String(length=16), nullable=True),
    sa.Column('picture', sa.String(length=20), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('aisles')
    op.drop_table('user')
    # ### end Alembic commands ###
