"""empty message

Revision ID: ccd86a721b91
Revises: af756d8b6de8
Create Date: 2020-12-17 18:26:56.504005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ccd86a721b91'
down_revision = 'af756d8b6de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titles', sa.JSON(), nullable=False, server_default='[]'))
        # batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('titles')

    # ### end Alembic commands ###
