"""empty message

Revision ID: f8711ad9c08b
Revises: b7330990195b
Create Date: 2020-12-31 21:07:40.393617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8711ad9c08b'
down_revision = 'b7330990195b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__rec', schema=None) as batch_op:
        batch_op.alter_column('times_eaten', existing_type=sa.INTEGER(), nullable=False, server_default=0)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__rec', schema=None) as batch_op:
        batch_op.alter_column('times_eaten',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
