

class GenericAisles:
    GENERIC_AISLES = {  # Should this be created outside class?
        'Produce': ['butterhead lettuce', ' pumpkin', 'Brussels sprouts', 'Roma tomatoes', 'apple', 'apples', 'apricot',
                    'asparagus', 'avocado', 'avocado', 'avocados', 'baby bella mushroom', 'baby bella mushrooms',
                    'baby carrots', 'baby kale', 'baby spinach', 'banana', 'banana peppers', 'bananas', 'beet', 'beets',
                    'bell pepper', 'blackberries', 'blanched green peas', 'blueberries', 'bok choy', 'bosc pears',
                    'broccoli', 'butternut squash', 'cabbage', 'california avocado', 'cantaloupe', 'carrot', 'carrots',
                    'cauliflower', 'cauliflower florets', 'celery', 'celery', 'chard', 'cherries', 'cherry tomatoes',
                    'chickpeas', 'chives', 'cilantro', 'collard green', 'concord grapes', 'corn', 'cranberries',
                    'cranberries', 'cremini mushroom', 'crimini mushrooms', 'cucumber', 'eggplant', 'eggplant',
                    'english cucumber', 'garlic', 'garlic', 'garlic cloves', 'ginger', 'granny smith apple',
                    'grapefruit', 'grapes', 'green apples', 'green beans', 'green maraschino cherries', 'green onion',
                    'green onions', 'green peas', 'green seedless grapes', 'green tomato pulp', 'green tomatoes',
                    'ground cherries', 'iceberg lettuce', 'jalapeño', 'kaffir lime leaves', 'kale', 'key lime juice',
                    'kiwi', 'kiwis', 'lady apple', 'leek', 'leeks', 'lemon', 'lemon grass', 'lemon peel', 'lettuce',
                    'lime', 'lime zest', 'mandarin orange', 'mandarin oranges', 'mango', 'mangos',
                    'maraschino cherries', 'melon', 'mushroom', 'mushrooms', 'napa cabbage', 'navel oranges', 'okra',
                    'onion', 'orange', 'orange turnip', 'oranges', 'parsley', 'parsley flakes', 'parsnip', 'parsnips',
                    'peach', 'peaches', 'pear', 'pearl onions', 'pearl sago', 'pearl sugar', 'pears', 'peas',
                    'pigeon peas', 'pineapple', 'pineapple chunks', 'pineapple rings', 'pineapple tidbits',
                    'pink grapefruit', 'plum', 'porcini mushrooms', 'portobello mushrooms', 'potato', 'potato',
                    'purple cabbage', 'radishes', 'raspberries', 'raspberries', 'red anjou pears', 'red apples',
                    'red cabbage', 'red delicious apples', 'red leaf lettuce', 'red maraschino cherries', 'red onion',
                    'red potato', 'red seedless grapes', 'rhubarb', 'ripe bananas', 'ripe peaches', 'ripe tomatoes',
                    'romaine lettuce', 'russet potato', 'rutabagas', 'seedless grapes', 'seedless green grapes',
                    'seedless red grapes', 'seedless watermelon', 'shiitake mushrooms', 'snow peas', 'sour orange',
                    'spinach', 'squash', 'strawberries', 'sugar pumpkin', 'sugar snap peas', 'sweet corn',
                    'sweet corn kernels', 'sweet onion', 'sweet onions', 'sweet peas', 'sweet potato', 'sweet potatoes',
                    'swiss chard', 'tomato', 'tomatoes', 'turnip', 'turnips', 'watermelon', 'white onion',
                    'white potato', 'whole button mushrooms', 'whole carrots', 'whole cranberries', 'whole kernel corn',
                    'whole mushrooms', 'whole onions', 'whole-kernel corn', 'yam', 'yams', 'yellow onion',
                    'yukon gold potatoes', 'zucchini'],
        'Meat': ['apple maple turkey sausages', 'apple maple turkey sausages', 'apple maple turkey sausages', 'beef',
                 'beef brisket', 'beef chuck', 'beef chuck roast', 'beef filet', 'beef frankfurters', 'beef kidney',
                 'beef oxtail', 'beef roast', 'beef sausage', 'beef shank', 'beef short ribs', 'beef sirloin',
                 'beef sirloin roast', 'beef sirloin steak', 'beef sirloin strips', 'beef sirloin tip steaks',
                 'beef skirt steak', 'beef steaks', 'beef suet', 'beef tenderloin', 'beef tenderloin steaks',
                 'beef tip', 'beef tongue', 'beef top sirloin steak', 'beef tripe', 'beef uncured hotdog',
                 'black cod fillet', 'bone-in beef shank', 'bone-in chicken breast', 'bone-in ham',
                 'boneless beef roast', 'boneless beef top loin', 'boneless chicken', 'boneless chicken thighs',
                 'boneless turkey roast', 'breakfast sausage', 'catfish fillets', 'chicken', 'chicken breast',
                 'chicken drumsticks', 'chicken gravy', 'chicken leg', 'chicken liver', 'chicken strips',
                 'chicken tenderloins', 'chicken tenders', 'chicken thighs', 'chicken wings', 'chinese sausages', 'cod',
                 'cod fillet', 'cod fillets', 'corned beef', 'corned beef', 'corned beef brisket',
                 'corned beef brisket', 'cranberry sausage stuffing', 'crawfish', 'crawfish tails',
                 'creole smoked sausage', 'extra-lean ground beef', 'extra-lean ground turkey breast', 'fish',
                 'ground beef', 'ground beef chuck', 'ground breakfast sausage', 'ground chicken',
                 'ground chicken breast', 'ground chicken liver', 'ground ham', 'ground lamb', 'ground pork',
                 'ground sausage', 'ground turkey', 'ground white meat turkey', 'ham', 'ham hock', 'ham hocks',
                 'ham spread', 'hot italian sausage', 'hot turkey sausage', 'italian meatballs', 'italian sausage',
                 'italian sausage links', 'italian turkey sausage', 'italian turkey sausage links', 'kielbasa sausage',
                 'lamb', 'lamb chops', 'lamb leg', 'lamb rib', 'lamb shanks', 'lamb stock', 'lean beef brisket',
                 'lean beef chuck', 'lean ground beef', 'lean ground turkey', 'lean pork sausage', 'maple roll sausage',
                 'meatball', 'mild italian sausage', 'orange roughy fillets', 'parma ham', 'polish sausage',
                 'pork chops', 'pork sausage', 'pork sausage links', 'rendered chicken fat', 'rotisserie chicken',
                 'salmon', 'salmon fillet', 'salmon roe', 'salmon steak', 'salmon steaks', 'salted cod fish', 'sausage',
                 'sausage casings', 'sausages', 'skinless boneless turkey breasts', 'skinless chicken leg quarters',
                 'skinless chicken thighs', 'skinless turkey breast', 'smoked bluefish', 'smoked ham hock',
                 'smoked ham shank', 'smoked salmon', 'smoked sausage', 'spicy ground pork sausage',
                 'spicy italian sausage', 'spicy pork sausage', 'spicy sausage', 'sweet italian sausage',
                 'swordfish steaks', 'tuna', 'turkey', 'turkey bacon', 'turkey breakfast sausage', 'turkey broth',
                 'turkey gravy', 'turkey legs', 'turkey liver', 'turkey sausage', 'turkey stock', 'turkey tenderloins',
                 'vegan sausage', 'vegetarian sausage links', 'white fish', 'white fish fillets', 'whole chicken',
                 'whole leg of lamb', 'whole smoked ham', 'whole turkey'],
        'Dairy': ['almond milk', 'blue cheese', 'brie cheese', 'butter', 'butterhead lettuce', 'buttermilk',
                  'camembert cheese', 'cashew butter', 'cheddar cheese', 'cheese', 'cheese curds',
                  'chocolate almond milk', 'chocolate buttercream', 'chocolate milk', 'coconut milk', 'coconut yogurt',
                  'colby cheese', 'cotija cheese', 'cottage cheese', 'cream cheese', 'egg', 'egg substitute',
                  'egg white', 'egg whites', 'egg yolk', 'egg yolks', 'eggnog', 'eggs', 'evaporated milk',
                  'fat-free cream cheese', 'fat-free milk', 'fat-free strawberry cream cheese', 'feta cheese',
                  'fontina cheese', 'fruit yogurt', 'full-fat coconut milk', 'goat cheese', 'goat milk',
                  'gorgonzola cheese', 'greek yogurt', 'havarti cheese', 'lemon flavored yogurt',
                  'lemon flavored yogurt', 'lemon yogurt', 'lemon yogurt', 'light coconut milk',
                  'liquid egg substitute', 'locatelli cheese', 'low-fat buttermilk', 'low-fat cottage cheese',
                  'low-fat cream cheese', 'low-fat lemon yogurt', 'low-fat lemon yogurt', 'low-fat milk',
                  'low-fat plain yogurt', 'low-fat ricotta cheese', 'margarine', 'mascarpone cheese',
                  'mild cheddar cheese', 'milk', 'milk chocolate', 'mizithra cheese', 'monterey jack cheese',
                  'mozzarella cheese', 'neufchatel cheese', 'non-fat cottage cheese', 'non-fat cottage cheese',
                  'non-fat lemon yogurt', 'non-fat lemon yogurt', 'non-fat milk', 'non-fat plain yogurt',
                  'non-fat ricotta cheese', 'oat milk', 'parmesan cheese', 'part-skim ricotta cheese',
                  'pasteurized egg', 'pasteurized egg yolks', 'pasteurized liquid egg whites', 'pepper jack cheese',
                  'pepper-jack cheese', 'pineapple yogurt', 'pineapple yogurt', 'plain low-fat yogurt',
                  'plain non-fat yogurt', 'plain whole-milk yogurt', 'plain yogurt', 'plant-based milk',
                  'provolone cheese', 'rice milk', 'rice milk', 'ricotta cheese', 'roquefort cheese', 'salted butter',
                  'skim milk', 'soy milk', 'soy milk powder', 'sticks butter', 'stilton cheese', 'strawberry yogurt',
                  'strawberry yogurt fruit spread', 'swiss cheese', 'thick coconut milk', 'tomato basil feta cheese',
                  'unflavored soy milk', 'unsalted butter', 'unsweetened almond milk', 'unsweetened coconut milk',
                  'unsweetened non-dairy milk', 'unsweetened plain almond milk', 'vanilla fat-free yogurt',
                  'vanilla rice milk', 'vanilla rice milk', 'vanilla soy milk', 'vanilla yogurt', 'vegan butter',
                  'vegan cheese', 'vegan cream cheese', 'vegan parmesan', 'white cheddar cheese', 'whole milk',
                  'whole-milk ricotta cheese', 'yogurt'],
        'Baked Goods': ['apple pie filling', 'bread', 'bread crumbs', 'butter flavored shortening',
                        'buttermilk biscuit dry mix', 'buttermilk biscuit mix', 'buttermilk pancake mix',
                        'buttermilk pancake mix', 'cinnamon graham crackers', 'corn bread', 'corn flour', 'cornbread',
                        'cornbread crumbs', 'cornbread muffin mix', 'cornbread muffin mix', 'cornmeal', 'cornmeal mix',
                        'cornstarch', 'french rolls', 'graham cracker crumbs', 'ground cornmeal',
                        'instant lemon pudding mix', 'jiffy corn muffin mix', 'lemon custard filling',
                        'lemon pie filling', 'lemonade mix', 'orange cream frosting', 'orange decorator sugar',
                        'orange food color', 'plain buttermilk doughnut', 'potato flakes', 'potato flour',
                        'potato starch', 'pumpkin pie filling', 'reduced-fat buttermilk baking mix',
                        'self-rising corn meal mix', 'self-rising cornmeal', 'vegan crumbles', 'yellow cornmeal'],
        'Dry Goods': ['almond butter', 'almond extract', 'apple butter', 'apple cider', 'apple cider vinegar',
                      'apple jelly', 'apple pie spice', 'applesauce', 'apricot jam', 'apricot preserves', 'avocado oil',
                      'banana extract', 'banana pepper juice', 'beans', 'bechamel sauce', 'beef bouillon', 'beef broth',
                      'beef gravy', 'black peppercorns', 'blue cheese salad dressing', 'blue corn posole', 'brown rice',
                      'butter beans', 'butter beans', 'butter flavored extract', 'butternut extract',
                      'butterscotch flavored extract', 'cauliflower rice', 'cauliflower rice', 'celery seed',
                      'cheese ravioli', 'cheese tortellini', 'cheese-filled tortellini', 'chicken bouillon',
                      'chicken bouillon granules', 'chicken bouillon powder', 'chicken broth', 'chicken broth',
                      'chicken stock', 'chili paste', 'chili puree', 'chili sauce', 'chunky peanut butter', 'coriander',
                      'corn bread', 'corn oil', 'corn oil spread', 'corn relish', 'corn syrup', 'corn tortillas',
                      'cornbread', 'cornbread crumbs', 'cornflakes cereal', 'cornflakes cereal crumbs',
                      'creamy peanut butter', 'crunchy peanut butter', 'crystallized ginger', 'dark corn syrup',
                      'dry egg noodles', 'dry non-fat milk powder', 'dry spinach noodles', 'egg noodles',
                      'fat-free chicken broth', 'fish sauce', 'fish stock', 'flax', 'flax eggs',
                      'four cheese alfredo sauce', 'garlic chili sauce', 'garlic naan', 'garlic paste', 'garlic pepper',
                      'garlic powder', 'garlic salt', 'ginger garlic paste', 'ginger oil', 'ginger paste',
                      'gingersnap cookie crumbs', 'graham crackers', 'grape-seed oil', 'ham base', 'hamburger buns',
                      'hash brown potatoes', 'honey graham cereal', 'instant oatmeal', 'instant potato flakes',
                      'instant powdered milk', 'lemon extract', 'lemon marmalade', 'lemon penne pasta',
                      'lemon penne pasta', 'lemon pepper', 'lemon vinaigrette', 'lemonade', 'lemonade concentrate',
                      'lemonade-flavor drink powder', 'light corn syrup', 'lime extract', 'low-sodium chicken broth',
                      'malted milk powder', 'mango chutney', 'mesquite-lime marinade', 'milk powder',
                      'natural peanut butter', 'non-fat dry milk powder', 'non-fat evaporated milk', 'nut butter',
                      'olive', 'onion powder', 'onion salt', 'orange extract', 'orange flower water',
                      'orange food coloring', 'orange jam', 'orange marmalade', 'pasta', 'peach chutney',
                      'peach preserves', 'peanut butter', 'pear preserves', 'pearl barley', 'peppercorns',
                      'pickled cucumber', 'pickled cucumber', 'pickled ginger', 'pickled ginger', 'pickled jalapeño',
                      'pickled jalapeño', 'pickled onions', 'pickled onions', 'pineapple preserves',
                      'pineapple-coconut nectar', 'plum jam', 'plum preserves', 'plum sauce', 'plum vinegar',
                      'powdered butter flavoring', 'powdered buttermilk', 'powdered egg substitute', 'powdered milk',
                      'powdered soy milk', 'pumpkin butter', 'pumpkin pie spice', 'pumpkin puree', 'pumpkin purée',
                      'pumpkin seeds', 'pumpkin seeds', 'ranch', 'raw whole pumpkin seeds', 'reduced-fat peanut butter',
                      'rhubarb jam', 'rice', 'rice milk', 'rice vinegar', 'salted peanut butter',
                      'shelled pumpkin seeds', 'smooth peanut butter', 'spiced applesauce', 'spinach fettuccine pasta',
                      'spinach fettuccine pasta', 'spinach lasagna noodles', 'spinach tortellini', 'spinach wraps',
                      'sugar frosted corn flake cereal', 'sweetened lemonade drink mix', 'sweetened lemonade powder',
                      'thai pepper garlic sauce', 'thin egg noodles', 'tomato and clam juice cocktail',
                      'tomato pasta sauce', 'tomato pasta sauce', 'tomato pasta sauce', 'tomato paste', 'tomato puree',
                      'tomato purée', 'tomato sauce', 'tomato-based chili sauce', 'tomato-based hot pepper sauce',
                      'tri-colored cheese-filled tortellini', 'unsalted crunchy peanut butter',
                      'unsweetened applesauce', 'unsweetened lemonade drink mix', 'vegan beef broth',
                      'vegetarian chicken flavor seasoning', 'vegetarian fish sauce', 'watermelon flavored syrup',
                      'white corn syrup', 'white cornmeal', 'white rice', 'whole black peppercorns',
                      'whole peppercorns', 'whole white peppercorns', 'wide egg noodles', 'yam extract'],
        'Frozen': ['french-fried onions', 'frozen', 'frozen blueberries', 'frozen blueberries', 'frozen chicken wings',
                   'frozen chicken wings', 'frozen cod fillets', 'frozen cod fillets', 'frozen corn', 'frozen corn',
                   'frozen corn kernels', 'frozen corn kernels', 'frozen green peas', 'frozen green peas',
                   'frozen hash brown potatoes', 'frozen hash brown potatoes', 'frozen limeade concentrate',
                   'frozen limeade concentrate', 'frozen pearl onions', 'frozen pearl onions', 'frozen raspberries',
                   'frozen raspberries', 'frozen raw crawfish', 'frozen raw crawfish', 'frozen snow peas',
                   'frozen snow peas', 'frozen strawberries', 'frozen strawberries', 'frozen unsweetened strawberries',
                   'frozen unsweetened strawberries', 'frozen whole kernel corn', 'frozen whole kernel corn',
                   'garlic croutons', 'lemon sherbet', 'lime sherbet', 'mozzarella cheese sticks', 'orange sherbet',
                   'pineapple sherbet', 'pineapple sorbet', 'pizza', 'sweet potato fries'],
        'Drinks': ['apple brandy', 'apple juice', 'apple schnapps', 'apricot brandy', 'apricot nectar', 'banana juice',
                   'banana liqueur', 'butterscotch schnapps', 'champagne', 'ginger ale', 'ginger ale soda',
                   'ginger ale soda', 'ginger ale soda', 'ginger juice', 'ginger juice', 'ginger liqueur',
                   'ginger paste', 'gingersnaps', 'grapefruit juice', 'lemon gin', 'lemon juice',
                   'lemon juice concentrate', 'lemon rum', 'lemon-lime flavored carbonated soda',
                   'lemon-lime flavored carbonated soda', 'lemon-lime flavored carbonated soda', 'lemonade mix',
                   'lemonade-flavor drink powder', 'lime juice', 'lime soda', 'lime soda', 'mango nectar',
                   'onion juice', 'orange bitters', 'orange juice', 'orange juice concentrate', 'orange liqueur',
                   'orange soda', 'orange soda', 'orange-flavored carbonated beverage',
                   'orange-flavored carbonated soda', 'orange-peach-mango juice', 'peach brandy', 'peach daiquiri mix',
                   'peach juice', 'peach schnapps', 'peach vodka', 'pickled ginger', 'pineapple juice', 'pink lemonade',
                   'raspberry ginger ale soda', 'raspberry ginger ale soda', 'raspberry ginger ale soda',
                   'sugar-free organic apple juice', 'sweetened lime juice', 'tomato juice',
                   'tomato-vegetable juice cocktail', 'tomato-vegetable juice cocktail', 'unsweetened apple juice',
                   'unsweetened apple juice concentrate', 'unsweetened pineapple juice', 'water'],
        'Snacks': ['blue corn tortilla chips', 'blue corn tortilla chips', 'butter flavored popcorn', 'chips',
                   'corn chips', 'corn chips', 'corn tortilla chips', 'corn tortilla chips', 'granola', 'guacamole',
                   'jalapeño cheese dip', 'milk chocolate chips', 'nacho cheese dip', 'nacho cheese sauce',
                   'plain popped popcorn', 'popped popcorn', 'unpopped popcorn', 'unpopped popcorn kernels',
                   'yogurt covered raisins']
    }

    def __init__(self, title=None, content=None):
        self.title = title
        self.content = content
        self.id = None
        self.order = 0
        self.store = None
        self.date_created = ''

    def get_all(self):
        all_generic = []
        for aisle, ingredients in self.GENERIC_AISLES.items():
            ingredients = ', '.join(set([' '.join([x.capitalize() for x in word.strip().split(' ')]) for word in ingredients]))
            # ingredients = ', '.join(set([word.strip().capitalize() for word in ingredients]))
            all_generic.append(GenericAisles(title=aisle, content=ingredients))
        return all_generic

    def get_all_dict(self):
        all_generic = {}
        for aisle, ingredients in self.GENERIC_AISLES.items():
            ingredients = ', '.join(set([' '.join([x.capitalize() for x in word.strip().split(' ')]) for word in ingredients]))
            # ingredients = ', '.join(set([word.strip().capitalize() for word in ingredients]))
            all_generic[aisle] = GenericAisles(title=aisle, content=ingredients)
        return all_generic

